"""The Field: the whole corpus on one stage, ported from agent-lab.

A single-page instrument that makes the statistical argument in three minutes: switch the oracle and
watch verdicts change, press rank then resample to see the leader change across 2,000 resampled task
sets, press flags to see runs that fail a trajectory test while still passing the oracle. Command center
watches one *live* run; the Field argues over *all* of them.

It needs one thing the rest of the API does not expose: the whole bundle (runs, tasks, harnesses) in
one payload, which `harnesslab.core.console.build_bundle` already produces. The console mounts the page
in an iframe -- live from this route, or from the document at /api/field/html inside a static export --
and the page keeps theme and oracle in step with the console through localStorage, which the same
origin shares.

The Field's own launch panel stays off (`launch: false`): launching belongs to Command center, whose
jobs the Field still reports through /api/status.
"""
from __future__ import annotations

import json
import os

from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse

from .paths import LAB_ROOT

router = APIRouter()

HERE = os.path.dirname(os.path.abspath(__file__))
FIELD_TEMPLATE = os.path.join(HERE, "field.html")
FONTS_CSS = os.path.join(HERE, "fonts.css")
DATA_MARKER = "__DATA__"
FONTS_MARKER = "__FONTS__"
DEFAULT_RESULTS = "prerecorded_mock"


def field_html(payload: dict) -> str:
    """field.html with its data slot filled.

    The file is a fragment (the hosted-artifact form it was authored in), so it gets the document
    skeleton here -- otherwise browsers render it in quirks mode. `{"live": true}` tells the page to
    fetch /api/bundle itself; an exported Field is handed `{"bundle": ...}` whole.
    """
    with open(FIELD_TEMPLATE, encoding="utf-8") as f:
        html = f.read()
    if html.count(DATA_MARKER) != 1:
        raise RuntimeError("field.html must carry exactly one __DATA__ slot")
    if html.count(FONTS_MARKER) != 1:
        raise RuntimeError("field.html must carry exactly one __FONTS__ slot")
    # The faces go in as base64 rather than as a stylesheet link: an exported Field opens from
    # file:// and must render identically with no network. Generated by frontend/scripts/gen_fonts.py.
    with open(FONTS_CSS, encoding="utf-8") as f:
        html = html.replace(FONTS_MARKER, f.read())
    body = html.replace(DATA_MARKER, json.dumps(payload).replace("</", "<\\/"))
    return ('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
            '<title>The Field -- harnesslab</title>\n</head>\n<body>\n' + body + '\n</body>\n</html>\n')


def _results_dir(name: str) -> str:
    """Resolve a results directory name, refusing anything that escapes data/runs."""
    safe = os.path.basename(name or "")
    if not safe or safe != name:
        raise HTTPException(status_code=400, detail="results must be a bare directory name")
    path = os.path.join(LAB_ROOT, "data", "runs", safe)
    if not os.path.isdir(path):
        raise HTTPException(status_code=404, detail=f"no such results directory: {safe}")
    return path


def _bundle(results: str, preview_chars: int) -> dict:
    from harnesslab.core.console import build_bundle          # imported lazily; LAB_ROOT is on sys.path by now

    return build_bundle([_results_dir(results)], lab_root=LAB_ROOT, preview_chars=preview_chars)


@router.get("/field", response_class=HTMLResponse)
def field_page(results: str = DEFAULT_RESULTS):
    """The Field, live: the page pulls its corpus from /api/bundle for this results directory."""
    _results_dir(results)                                     # refuse bad names before any HTML goes out
    return HTMLResponse(field_html({"live": True, "results": results, "launch": False}))


@router.get("/api/bundle")
def bundle(results: str = DEFAULT_RESULTS, preview_chars: int = 900):
    """The Field's whole-corpus payload: runs, tasks, harnesses (plus trajectories/features).

    One directory at a time, because the Field's resampling treats the directory as the corpus.
    """
    return _bundle(results, preview_chars)


@router.get("/api/status")
def status(results: str = DEFAULT_RESULTS):
    """The Field's cheap poll: "has the corpus changed?", plus the jobs Command center is running.

    The page refetches /api/bundle when `version` moves, so this must stay free of ledger parsing.
    """
    from .app import JOBS, job_public                          # late: app.py includes this router

    path = _results_dir(results)
    index = os.path.join(path, "index.jsonl")
    n_runs, mtime = 0, 0.0
    if os.path.exists(index):
        mtime = os.path.getmtime(index)
        with open(index, "rb") as f:
            n_runs = sum(1 for line in f if line.strip())
    jobs = [job_public(j) for j in JOBS.values()]
    running = [r for j in jobs for r in (j.get("running") or [])]
    return {"version": f"{n_runs}:{int(mtime)}", "runs": n_runs, "jobs": jobs, "running": running}


def field_export(results: str, preview_chars: int = 0) -> tuple[str, dict]:
    """One self-contained Field: the bundle goes in whole and the page reduces it itself, the same
    code path the live server uses. Tool-output previews are dropped (preview_chars=0) because the
    Field never shows them and they are most of the payload."""
    b = _bundle(results, preview_chars)
    b["static"] = True
    return field_html({"bundle": b}), b


@router.get("/api/field/html")
def field_static(results: str = DEFAULT_RESULTS):
    """The Field as one document, for `--export`: the console snapshot embeds one per results dir."""
    html, b = field_export(results)
    return {"results": results, "runs": len(b["runs"]), "html": html}


def export_field(results: str, out_path: str, preview_chars: int = 0) -> dict:
    html, b = field_export(results, preview_chars)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return {"path": out_path, "bytes": len(html.encode("utf-8")),
            "runs": len(b["runs"]), "tasks": len(b["tasks"]),
            "harnesses": len(b["harnesses"]), "results": results}
