"""The harness recorded on a captured run's start span: configuration only.

The importer's `harness_from_fingerprint` copies OBSERVED extremes (max steps, longest observation,
tools that happened to be used) into config fields, so every Claude Code session gets its own hash
and the Harness lab fragments into one bucket per session. Here, config fields hold only what the
harness IS; what it DID is the observed fingerprint the writer puts on the end span.

The Harness lab groups by harness id first and hash second, so the Claude Code version (which is in
the id, e.g. claude-code@2.1.x) still separates versions.

KNOWN, AND NOT SETTLED HERE: `policy` breaks the rule this module states. It is a real HarnessConfig
field, so it is hashed, but it is derived from `permission_modes` -- an observation accumulated over
the whole file. An operator who starts in `default` and later switches to `bypassPermissions` flips
it from "strict" to "permissive", so the same run regenerated by a later backfill hashes differently
and the Harness lab re-fragments, which is the exact failure this module exists to prevent.

Left as it is on purpose. The honest fix depends on what a harness means when its policy changed
mid-session: the mode in effect at the segment's start (stable, and arguably what it was configured
as), the most permissive mode ever reached (what it could do, and what a safety reviewer wants), or
"unknown" with the modes left in observed_config where they cannot reach the hash. That is the
operator's call, not a detail to settle in a review fix. Measured incidence on the corpus this was
written against: 150 real sessions, none carrying any permission mode, so the drift is currently
unreachable in practice.
"""
from __future__ import annotations

from harnesslab.backend.importers import common as C, qwen_code
from harnesslab.core.harness import content_hash


def _claude_permission_modes(sess) -> tuple:
    modes = list(sess.extra.get("permission_modes") or [])
    policy = "permissive" if "bypassPermissions" in modes else ("strict" if modes else "unknown")
    return policy, {"permission_modes": modes}


def _qwen_decision(sess) -> tuple:
    """Qwen records the approval decision per call in systemPayload.uiEvent.decision. `permissive`
    only when an auto-accepting decision was actually OBSERVED -- the honesty rule in
    importers/__init__: we never claim a boundary was removed that we did not see removed."""
    decisions = list(sess.extra.get("decisions") or [])
    if not decisions:
        return "unknown", {}
    permissive = any(d in qwen_code.PERMISSIVE_DECISIONS for d in decisions)
    return ("permissive" if permissive else "strict"), {"decisions": decisions}


def _codex_approval(sess) -> tuple:
    """Codex records its boundary in `turn_context`: `approval_policy` and `sandbox_policy.type`.
    Measured over all 1,423 rollouts on this machine, approval_policy is one of
    {on-request, never} and sandbox_policy.type is one of
    {workspace-write, danger-full-access, read-only} -- nothing else occurs.

    Same honesty rule as the other two: `permissive` only when a boundary was OBSERVED removed --
    approvals turned off, or the sandbox opened to full access. A recorded policy that removes
    neither is `strict`; a rollout that records no policy at all is `unknown`, not `strict`.
    """
    approval = str(sess.extra.get("approval_policy") or "")
    sandbox = str(sess.extra.get("sandbox_policy") or "")
    if not approval and not sandbox:
        return "unknown", {}
    observed = {"approval_policy": approval, "sandbox_policy": sandbox}
    permissive = approval == "never" or sandbox == "danger-full-access"
    return ("permissive" if permissive else "strict"), observed


def _none(sess) -> tuple:
    """The honest answer for a source whose trace says nothing about its policy."""
    return "unknown", {}


#: descriptor `policy` name -> strategy. A new adapter must name one explicitly, so it cannot
#: inherit Claude Code's permission-mode rule by accident. Adding a name here without a descriptor
#: that uses it is harmless; the reverse is not.
POLICIES = {"claude_permission_modes": _claude_permission_modes,
            "codex_approval": _codex_approval,
            "qwen_decision": _qwen_decision,
            "none": _none}


def capture_harness(sess) -> dict:
    from .adapters import BY_NAME          # local import: adapters imports importers, not us
    ad = BY_NAME.get(sess.source)
    policy, observed = POLICIES[ad.policy if ad else "none"](sess)
    h = {
        "id": C.harness_id_for(sess),
        "system_prompt": "",
        "tools": sorted(sess.declared_tools or []),
        "policy": policy,
        "max_steps": int(sess.max_steps_declared or 0),
        "max_total_tokens": 0,
        "context_window": 0,
        "observation_chars": 0,
        "temperature": float(sess.temperature) if isinstance(sess.temperature, (int, float)) else 0.0,
        "max_tokens_per_call": 0,
        "include_file_listing": False,
        "notes": f"captured from {sess.source}; the observed fingerprint is on the end span",
        "sentinel": {},
        "observed_config": dict(observed, entrypoint=sess.extra.get("entrypoint", ""),
                                agent_version=sess.agent_version),
    }
    h["hash"] = content_hash(h)
    return h
